plugins {
    id 'java-library'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id
def customerModName = providers.gradleProperty('mod_name').get()

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

repositories {
    maven {
        name = 'Minecraft Libraries'
        url = 'https://libraries.minecraft.net/'
        content {
            includeGroupAndSubgroups('org.lwjgl')
        }
    }
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter {
            includeGroupAndSubgroups('org.spongepowered')
        }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org'
                },
                maven {
                    name = 'NeoForge'
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter {
            includeGroup('org.parchmentmc.data')
        }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup('maven.modrinth')
        }
    }
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases'
    }
}

['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations."${variant}".outgoing {
        capability("${project.group}:${base.archivesName.get()}:${project.version}")
        capability("${project.group}:${mod_id}-${project.name}-${minecraft_version}:${project.version}")
        capability("${project.group}:${mod_id}:${project.version}")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

tasks.named('sourcesJar', Jar) {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${customerModName}" }
    }
}

tasks.named('jar', Jar) {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${customerModName}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : customerModName,
                'Specification-Vendor'  : 'Viking Kittens',
                'Specification-Version' : project.version,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor' : 'Viking Kittens',
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
