plugins {
    id 'customers-common'
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

configurations.compileClasspath.extendsFrom(configurations.common)
configurations.testCompileClasspath.extendsFrom(configurations.common)
configurations.testRuntimeClasspath.extendsFrom(configurations.common)
