plugins {
    id 'base'
    id 'net.neoforged.moddev' version '2.0.142' apply false
    id 'com.diffplug.spotless' version '8.9.0' apply false
}

tasks.register('runClientNeoForge') {
    group = 'customers runs'
    description = 'Runs the Customers NeoForge client.'
    dependsOn(':neoforge:runClient')
}

tasks.register('runServerNeoForge') {
    group = 'customers runs'
    description = 'Runs the Customers NeoForge server.'
    dependsOn(':neoforge:runServer')
}

tasks.register('runDataNeoForge') {
    group = 'customers runs'
    description = 'Runs Customers data generation for NeoForge.'
    dependsOn(':neoforge:runClientData', ':neoforge:runData')
}

tasks.register('buildNeoForge') {
    group = 'build'
    description = 'Builds the Customers NeoForge JAR.'
    dependsOn(':neoforge:build')
}

tasks.register('buildAllLoaders') {
    group = 'build'
    description = 'Builds the Customers NeoForge JAR.'
    dependsOn('buildNeoForge')
}

tasks.register('testAllLoaders') {
    group = 'verification'
    description = 'Runs common and NeoForge tests.'
    dependsOn(':common:test', ':neoforge:test')
}
